version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: "HH-DB"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    container_name: "HH-API"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/myapp
      - ./api/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  view:
    build: 
      context: ./view/
      dockerfile: Dockerfile
    volumes:
      - ./view:/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "8000:3000"
    depends_on:
      - api

volumes:
  mysql-data:
    driver: local
